### ISSUE TITLE
submit的时候不会自动带上极验的三个参数

### ISSUE THREAD

**Issue by period331** [GeeTeam/gt-python-sdk#1]
我现在在用flask为框架，使用极验的时候，显示验证码验证都没有问题，就是在提交的时候，极验的三个参数不会随着我的登陆参数一起提交导致验证失败。

![qq20150413-1](https://cloud.githubusercontent.com/assets/2114380/7118668/64f847a0-e233-11e4-80b9-3f157eedc81b.png)
![qq20150413-2](https://cloud.githubusercontent.com/assets/2114380/7118672/67961fdc-e233-11e4-9012-95ef025a1ffe.png)

**Comment by zhangcx93** [comment]
你把验证码的script放在form标签里了么？如果是的话，会在form里添加三个input，至少前端会把三个参数传出去

**Comment by period331** [comment]
将scrip放入form中后解决
:+1:
